alert ("Archivo hoisting.js");
//HOISTSING

/*HOISTING SIGNIFICA ELEVAR

DENTRO DE JS, DESCRIBE EL COMPORTAMIENTO QUE TIENEN LAS VARIABLES RESERVADA "VAR". NO APLICA PARA LET NI CONST

CADA VARIABLE DECLARADA CON VAR, SE LEE INMEDIATAMENTE AL EJECUTAR EL PROGRAMAM.
SIN IMPORTAR EN DONDE FUE DEFINIFDA.*/

x=10;
console.log(x);
 var x = 8;
 x = 10;
 console.log("Holaa");